### PR TITLE
Init CLI

### PR DESCRIPTION
**Pull request by Henni**
Initial cli setup.

### CODE REVIEW

**Comment by Henni** [comment]
I have to fix the merge conflicts first...

**Comment by Henni** [comment]
fixed the merge conflicts.
we now have two config files. I will work on removing the old one after this PR is merged.

**Comment by Henni** [comment]
reopened PR as branch was mistakenly deleted before.

**Review by simonzachau — CHANGES_REQUESTED** [review]
`SyntaxError: Identifier 'config' has already been declared`

**Review by krishenk — APPROVED** [review]
Looks good to me.

**Review by simonzachau — CHANGES_REQUESTED** [review]
`node cli.js` works fine, but `mcm-relationships` not for me

**Comment by Henni** [comment]
removed a function parameter which isn't needed anymore as noted by @Sandr00 
@simonzachau I'd still like to merge. It works on my side and I'd like to debug this later on your machine.

**Review by simonzachau — APPROVED** [review]

**Pull request merged**
