### PR TITLE
Classification

### PR DESCRIPTION
**Pull request by RBirkeland**
Made a new pull request because some weird merging happen when switching which computer I worked from..

Added a naive bayes classifier:
* Uses the current small dataset of synonyms for teacher, student, wrote and performed.
* Can add more synonyms by using addSynonymsToArray(array, word). Will add all unique synonyms of the word by using wordnet into the specified array.
* Classify(word) will return a list of all the labels and the certainty that it belongs to each label. (However this is not very accurate unless the training set is larger, therefor use addSynonymsToArray)

[ { label: 'teach', value: 0.08333333333333333 },
  { label: 'student', value: 0.041666666666666664 },
  { label: 'perform', value: 0.041666666666666664 },
  { label: 'wrote', value: 0.04166666666666666 } ]

### CODE REVIEW

**Review by ansjin — APPROVED** [review]
Looks okay to me, Only thing remaining is the codacy issue, which can be resolved. Before merging please fix that 1 issue.

**Comment by Gillian0023** [comment]
strange codacy issue about console, still need to be fixed

**Comment by ansjin** [comment]
I think that issue can be ignored. What do you say @Sandr00 and @Henni . Is there a fix for that ?

**Comment by Sandr0x00** [comment]
We should ignore the codacy console issues!
Since codacy itself says: If you're using Node.js, you should disable this rule, because console is used to output information to the user and so is not strictly used for debugging purposes.

**Pull request merged**
