### PR TITLE
Algorithms improvment and chaining

### PR DESCRIPTION
**Pull request by ansjin**
1. Ollie, Date_Event Extraction and Co-reference Resolution improved. 
2. Added the part for calling them from the main application and linked with the parser.

### CODE REVIEW

**Review by Sandr0x00 — CHANGES_REQUESTED** [review]
We should use promises in the algorithm calls. Currently working on that.

**Comment by Henni** [comment]
+235,491 lines seems a bit much :wink:

Let's just add a few example entries.

**Comment by Sandr0x00** [comment]
@Henni, is it ok now in the test folder?

**Review by Henni — APPROVED** [review]
Let's get this in and reiterate later.

**Review by Sandr0x00 — APPROVED** [review]

**Pull request merged**
